server:
  port: 8090

spring:
   application:
     name: emp-provider
   datasource:
       driver-class-name: com.mysql.jdbc.Driver
       url: jdbc:mysql://localhost:3306/springcloud
       username: root
       password: root
       type: com.alibaba.druid.pool.DruidDataSource
   jpa:
       hibernate:
          ddl-auto: update
       show-sql: true
             
eureka:
   client: #客户端注册进eureka服务列表内
      service-url:
         defaultZone: http://127.0.0.1:8092/eureka/
   instance:
      instance-id: ${spring.cloud.client.ipAddress}:${spring.application.name}:${spring.application.instance_id:${server.port}}
      prefer-ip-address: true
